name: ${project.artifactId}
version: ${project.version}
main: net.okocraft.deathmessages.Main
author: LazyGon
api-version: '1.16'
softdepend: ["WorldGuard"]

commands:
  toggledeathmessage:
    aliases: ["tdm"]
    permission: "deathmessageflags.toggle"
    description: デスメッセージが聞こえるかどうかを切り替えるコマンド。

permissions:
  deathmessageflags.toggle:
    default: true
    description: tdmコマンドの権限